components/samenhang-layout.js
components/welke-layout.js
pages/circulaire-windturbines/samenhang-maatregelen.js
pages/circulaire-windturbines/welke-overheid-heeft.js
pages/houtbouw/samenhang-aantal-houtbouwmaatregelen.js
pages/houtbouw/welke-overheid.js

Combine welke-overheid pages

---

components/layouts/measures-layout.js

changed the text to what Yvonne suggested & capitalised regions to make it consistent. it was causing a bug in the filters.

changed text

---

components/layouts/measures-layout.js

Now when the user clicks on a suggested title the searchValue updates

Added onclick

---

components/layouts/measures-layout.js

text stays in input after clicking out of it

fix click out of input

---

components/layouts/measures-layout.js
components/measure-overview.js
components/search-filter.js
pages/measures/[id].jsx

created component measure overview.

Refactor measures id page

---

components/layouts/theme-index-layout.js
components/section-bottom-theme-index.js

Created a component for the bottom section of the theme index page. Did this as the design is likely to change and the two sections (the tree cards and the three 'views') will swap places.

Create component for current overview section on theme layout

---

components/measure-table.js
pages/measures/[id].jsx

put the table into a component. Will wait to add custom designs for mobile/desktop after feedback from design team.

Measure table component

---

components/layouts/measures-layout.js

Search terms : Ignore location = true, title weight = 2, introductie_juridische_maatregel weight = 1.5 all other attributes have weight =1, threshold = 0.4

search params 2 (not for prod)

---

components/layouts/measures-layout.js

Ignore location = true, title weight = 2, introductie_juridische_maatregel weight = 1.5 all other attributes have weight =1, threshold 0.2

filter params (not for prod)

---

data.js
studio/schemas/measure.js

find and replace

---

components/policy-list.js
components/section-types-list.js
pages/matrassen/index.js
pages/measures/[slug].js
pages/measures/matrassen.js

Linked up matrassen page. The content all needs updating but the measures/matrassen page displays the measured from the cms.

Add matress page

---

components/juridische-houdbaarheid-tooltip.js
components/juridische-invloed-tooltip.js
components/layouts/measures-layout.js
components/layouts/theme-index-layout.js
components/measure-table.js
components/nav.js
components/nieuw-tooltip.js
components/policy-list.js
components/r-ladder-tooltip.js
components/section-bottom-theme-index.js
components/theme-card.js
pages/about/[slug].js
pages/index.js
pages/measures/[slug].js

More fixes

---

components/layouts/welke-layout.js
global.css
pages/circulaire-windturbines/welke-overheid-heeft.js
pages/houtbouw/welke-overheid.js
pages/matrassen/index.js
pages/matrassen/welke-overheid-heeft.js
pages/measures/windturbines.js

Got the overview pages dynamically generated. Still need to add in the borders on the design and the white dots.

Overview page windmilss

---

components/layouts/welke-layout.js
components/measure-links-dropdown.js
components/section-bottom-theme-index.js
pages/circulaire-windturbines/index.js
pages/houtbouw/index.js
pages/matrassen/index.js
pages/matrassen/welke-overheid-heeft.js
studio/components/logo.jsx
studio/sanity.config.js

little refactor and a content fix.

Pass data as props to theme page

---

components/layouts/measures-layout.js
components/layouts/samenhang-layout.js
components/layouts/welke-layout.js
components/overview-page-header.js
pages/circulaire-windturbines/samenhang-maatregelen.js
pages/circulaire-windturbines/welke-overheid-heeft.js
pages/houtbouw/samenhang-aantal-houtbouwmaatregelen.js
pages/houtbouw/welke-overheid.js
pages/matrassen/samenhang-matrassen.js
pages/matrassen/welke-overheid-heeft.js
pages/measures/houtbouw.js
pages/measures/matrassen.js
pages/measures/windturbines.js

Made component. Going to leave in draft as I will also do a bit more work on the icons and their sizes on mobile etc.

Make overview header component

---

components/layouts/theme-index-layout.js
components/link-icon.js
components/nav.js
components/partners.js
pages/en/index.js

updated logo
fixed bugs:
- type in work dutch
- link to contact page -> email

Last en page fixes

---

components/homepage-header.js
components/layouts/layout.js
components/nav.js
pages/en/index.js

I finally got around to reducing the NAV to one case with conditional styling. 
I figured it would be easier when we start adding the NAV components to Sanity.

Nav refactor 2.0

---

components/nav.js
components/overview-page-header.js

I think that is the last of them

Bug fixes 

---

components/nieuw-tooltip.js
pages/index.js
pages/privacy-policy/index.js

Fixed the broken link in new button.
added external link icon to external links in privacy page

Hotfix broken link

---

components/cookie-banner.js

Reverts Dark-Matter-Labs/circulaw#311

Revert "remove cookie banner from preview"

---

components/beta-banner.js
components/footer.js
components/overview-page-header.js
components/partners.js
global.css
pages/index.js

Added top button to all pages, 
reduced global margin on mobile,
added drop down to navigate between overviews on mobile

Mobile quick fixes

---

components/partners.js
studio/schemas/documents/about-pages.js
studio/schemas/documents/english-page.js
studio/schemas/documents/navigation.js
studio/schemas/documents/news.js
studio/schemas/documents/partners.js
studio/schemas/documents/thema.js
studio/schemas/objects/link.js
studio/schemas/objects/nav-item.js
studio/schemas/objects/partner.js
studio/yarn.lock

update sanity field names and descriptions to dutch. 
Keeping in draft as there are two fields that I am waiting for confirmation.

Sanity renaming

---

studio/package.json
studio/yarn.lock

remove latest package which was causing security issues

remove latest package

---

components/beta-banner.js
components/custom-button.js
components/footer.js
components/home-page-about-section.js
components/homepage-header.js
components/lang-switch.js
components/layouts/theme-index-layout.js
components/nav.js
components/section-bottom-theme-index.js
components/section-types-list.js
pages/circulaire-matrasketen/samenhang-matrassen.js
pages/circulaire-windturbines/index.js
pages/circulaire-windturbines/samenhang-maatregelen.js
pages/en/index.js
pages/houtbouw-stimuleren/samenhang-aantal-houtbouwmaatregelen.js
pages/index.js
tailwind.config.js

reduced brak point to 910px using lgNav variable in tailwind css
Changed mobile menu from Headless ui Disclosure to Popover
Reduced size of beta banner 
Made beta banner disappear on scroll
Nav bar is sticky on all pages, desktop and mobile. 
Reduced image size on en page to improve performance

Nav improvements

---

components/home-page-about-section.js
components/layouts/layout.js
package.json
pages/circulaire-matrasketen/samenhang-matrassen.js
pages/circulaire-windturbines/samenhang-maatregelen.js
pages/houtbouw-stimuleren/samenhang-aantal-houtbouwmaatregelen.js
pages/privacy-policy/index.js
utils/global-meta.js
yarn.lock

- Better strategy for hardcoded URLs
- Fix typo in privacy page
- Fix warning in site title
- remove package not in use

Minor improvements

---

components/faq-page.js
components/nav.js
lib/queries.js
package.json
studio/schemas/documents/faq.js
studio/schemas/index.js
studio/schemas/objects/faq-item.js
studio/schemas/objects/faq-section.js
studio/yarn.lock
tailwind.config.js
yarn.lock

Updated the FAQ page schema of the CMS to accommodate accordions. 
Updated the design with headless ui disclosures allowing the user to open and close the faq question. 
Added optional headings to make FAQ sections. 
Changed from headless ui to MUI component for the FAQ page.

Faq page accordions

---

components/feedback-block.js
components/instrument-preview.js
components/instrument.js
components/layouts/theme-index-layout.js
components/measure-overview.js
components/measure-table.js
pages/measures/houtbouw.js
pages/measures/matrassen.js
pages/measures/windturbines.js

Completed the two quick fixes. 
1. changing the order of the overview cards
2. Moving a field from the measure table to the measure overview on the instruments pages
Leaving in draft as waiting on some potential copy changes from Marlies for task 1

Quick fixes from user research

---

components/measure-overview.js
components/section-types-list.js
studio/schemas/objects/pdf-block.js

Fixed the issue that Arjan raised r.e. the button on the theme card.

Fix theme button

---

components/layouts/welke-layout.js
components/measure-overview.js
components/section-types-list.js
studio/schemas/objects/pdf-block.js

I made this branch to fix the layout on the welke overheid page and the buttons in the homepage cards. 
Going directly to production so that we can keep working on staging.

Bugs in production

---

components/expertise-page/explination-text.js
components/expertise-page/tab-button.js
components/expertise-page/tab-layout.js
components/layouts/expertise-layout.js

improve structure of expertise page and add use transition to tab state.

Categorie refactor

---

lib/portable-text/portable-text-marks.js
lib/portable-text/portable-text-types.js
lib/portable-text/pt-components.js
lib/queries.js
studio/schemas/documents/measure.js
studio/schemas/objects/green-box.js
studio/schemas/objects/small-paragraph.js

Internal link added to portable text

Reference instruents

---

components/eu-law/highlights-small-card.js
components/layouts/layout.js
components/nav/index.js
lib/queries.js

Added the list of eu laws to the desktop and mobile nav. 
Added an overview link to link to overview page.

Eu nav dropdown

---

components/home-page-about-section.js
components/layouts/expertise-layout.js
pages/index.js
studio/schemas/documents/instrument.js

Homepage improvements

---

app/[productChain]/[thema]/instrumenten/[slug]/page.js
components/layouts/theme-index-layout.js
components/nav/footer.js
components/nav/index.js
components/theme-page/theme-sponsors.js
global.css
tailwind.config.js

Add animation to logos

---

.husky/pre-commit
app/api/algolia-indexing/route.js
package.json
studio/schemas/documents/news-item.js
yarn.lock

add condition for algolia to index only on production deployments
update husky to v9

Add condition for algolia indexing
